### ISSUE TITLE
EdgyBot Bounty

### ISSUE THREAD

**Issue by gsrhax** [gsrhax/No-ADS-YouTube#5]
@EdgenuityScripts Hey, I'm GSRHaX, creator of EdgyBot, You released a cracked version of it and I wanted it taken down but for payment, yet you removed it on your own for no reason. I wanted to basically have you work with me to ensure it doesn't get cracked by other people. Please contact me as soon as possible. Thank you for your time.

**Comment by EdgenuityScripts** [comment]
Hi, here's my advice:

1. I would advise against the use of obfuscator.io as it can be easily de-obfuscated. While I am not familiar with any alternatives, I recommend exploring more secure methods of code obfuscation.

2. It is important to ensure that payment is received before providing any access to the tool, even in an obfuscated form. I suggest sending users a new link containing a private download to EdgyBot once payment has been confirmed.

3. To further enhance security, I recommend implementing a product key or token system for downloads of the tool. This system can be used for encryption/decryption as well as activation, and can be restricted to only one IP address to prevent unauthorized access to the obfuscated source code. While I understand that this may be a challenging implementation, it is a necessary step to make the code more secure.

4. It is important that the API key of the user database be kept confidential and not exposed to the client, mainly for privacy reasons. During my work on the cracked/free version of EdgyBot, I discovered this, which allowed me to crack the activation system easily.

**Comment by gsrhax** [comment]
Hey, thanks so much for your advice, but why did you remove the cracked
version. Don’t get me wrong I am grateful for two reasons, one being the
payment and another being not having EdgyBot deobf online so that Edgenuity
devs ( who are too lazy to even look at the source code the way you did)
from seeing it and fully patching it, but it’s just confusing that you
posted it and removed it 😭
